version: "2"

services:
  topics:
    build: ./topics_classifier/.
    image: topics
    hostname: topics
    links:
      - mongodb:mongodb
    networks:
      - front
  mongodb:
    build: ./mongodb/.
    image: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    networks: 
      - front

networks:
  front:
